spring:
  datasource:
    url: jdbc:mysql://localhost:3306/first
    username: adeka
    password: adeka
    driver-class-name: org.mysql.Driver
application:
  security:
    jwt:
      secret-key:
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
